In [2]:
import pandas as pd
import numpy as np
from luwiji.pandas import illustration

In [4]:
df=pd.read_csv("cereal.csv")
df.head()

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.0,FDA_25,3,1.0,0.33,68.402973
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.0,FDA_0,3,1.0,1.00,33.983679
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.0,FDA_25,3,1.0,0.33,59.425505
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.0,FDA_25,3,1.0,0.50,93.704912
4,Almond Delight,R,C,110,2,2,200,1.0,14.0,8.0,NaN,FDA_25,3,1.0,0.75,34.384843

In [7]:
df.groupby(["mfr","weight"]).mean()

              calories   protein       fat      sodium     fiber      carbo  \
mfr weight
A   1.00    100.000000  4.000000  1.000000    0.000000  0.000000  16.000000
G   1.00    107.894737  2.210526  1.315789  202.105263  1.078947  14.605263
    1.25    130.000000  3.000000  2.000000  170.000000  1.500000  13.500000
    1.33    130.000000  3.000000  2.000000  210.000000  2.000000  18.000000
    1.50    140.000000  3.000000  1.000000  190.000000  4.000000  15.000000
K   1.00    101.111111  2.555556  0.444444  168.333333  2.500000  14.555556
    1.30    140.000000  3.000000  1.000000  170.000000  2.000000  20.000000
    1.33    126.666667  3.000000  1.000000  223.333333  4.333333  16.333333
    1.50    160.000000  3.000000  2.000000  150.000000  3.000000  17.000000
N   0.83     80.000000  2.000000  0.000000    0.000000  3.000000  16.000000
    1.00     88.000000  3.000000  0.200000   45.000000  4.200000  16.000000
P   1.00    105.714286  2.285714  0.714286  136.428571  2.000000  13.714286
    1.25    120.000000  3.000000  2.000000  160.000000  5.000000  12.000000
    1.33    120.000000  3.000000  1.000000  200.000000  6.000000  11.000000
Q   0.50     50.000000  1.500000  0.000000    0.000000  0.500000  11.500000
    1.00    110.000000  3.000000  2.333333  123.333333  1.616667  11.600000
R   1.00    115.000000  2.500000  1.250000  198.125000  1.875000  17.625000

               sugars      potass     shelf      cups     rating
mfr weight
A   1.00     3.000000   95.000000  2.000000  1.000000  54.850917
G   1.00     7.526316   75.000000  2.000000  0.894737  34.874029
    1.25    10.000000  120.000000  3.000000  0.500000  30.450843
    1.33     8.000000  100.000000  3.000000  0.750000  37.038562
    1.50    14.000000  230.000000  3.000000  1.000000  28.592785
K   1.00     6.722222   86.388889  2.222222  0.822222  45.840709
    1.30     9.000000   95.000000  3.000000  0.750000  36.471512
    1.33    10.333333  186.666667  2.666667  0.696667  40.322336
    1.50    13.000000  160.000000  3.000000  0.670000  30.313351
N   0.83     0.000000   95.000000  1.000000  1.000000  68.235885
    1.00     2.200000  157.500000  1.800000  0.734000  67.915104
P   1.00     7.857143   80.714286  2.285714  0.727143  42.370579
    1.25    10.000000  200.000000  3.000000  0.670000  40.917047
    1.33    14.000000  260.000000  3.000000  0.670000  37.840594
Q   0.50     0.000000   32.500000  3.000000  1.000000  61.880879
    1.00     8.600000   88.333333  2.166667  0.765000  36.594360
R   1.00     6.125000  102.142857  2.000000  0.871250  41.542997